name: Python test

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**/*.md"
      - "documentation/**"
  pull_request:
    branches:
      - master
    paths-ignore:
      - "**/*.md"
      - "documentation/**"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - '3.12'

    steps:
      - uses: actions/checkout@v5

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --frozen --extra dev

      - name: Linting and formatting with ruff
        run: |
          ruff check .
          ruff format . --diff

      - name: Linting with pyright
        run: |
          pyright --warnings --project pyproject.toml

      - name: Dependency scanning with safety
        run: |
          safety --disable-optional-telemetry check -r uv.lock --full-report

      # - name: Test with pytest
      #   run: |
      #     pytest --verbose . --junitxml=junit.xml

      # - name: Publish Test Report
      #   uses: mikepenz/action-junit-report@v4
      #   if: always() # always run even if the previous step fails
      #   with:
      #     report_paths: "junit.xml"
